apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
  labels:
    app: istio-ingress
spec:
  releaseName: istio
  chart:
    spec:
      chart: istio/gateway
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 10m0s
  values:
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cb-tls
      hosts:
        - "cb-interview.com"
