apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: istio/gateway
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  interval: 10m0s
  values:
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: istio-ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-cb-interview-cert
      hosts:
        - "cb-interview.com"
