apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: istio/gateway
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  values:
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system
