apiVersion: v1
kind: Service
metadata:
  name: servicey-service
  namespace: servicey
spec:
  type: ClusterIP
  selector:
    app: servicey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
